// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// CreateUsersWithArrayInputReader is a Reader for the CreateUsersWithArrayInput structure.
type CreateUsersWithArrayInputReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateUsersWithArrayInputReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	result := NewCreateUsersWithArrayInputDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result
}

// NewCreateUsersWithArrayInputDefault creates a CreateUsersWithArrayInputDefault with default headers values
func NewCreateUsersWithArrayInputDefault(code int) *CreateUsersWithArrayInputDefault {
	return &CreateUsersWithArrayInputDefault{
		_statusCode: code,
	}
}

/* CreateUsersWithArrayInputDefault describes a response with status code -1, with default header values.

successful operation
*/
type CreateUsersWithArrayInputDefault struct {
	_statusCode int
}

// Code gets the status code for the create users with array input default response
func (o *CreateUsersWithArrayInputDefault) Code() int {
	return o._statusCode
}

func (o *CreateUsersWithArrayInputDefault) Error() string {
	return fmt.Sprintf("[POST /user/createWithArray][%d] createUsersWithArrayInput default ", o._statusCode)
}

func (o *CreateUsersWithArrayInputDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
