// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// CreateUsersWithListInputReader is a Reader for the CreateUsersWithListInput structure.
type CreateUsersWithListInputReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateUsersWithListInputReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	result := NewCreateUsersWithListInputDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result
}

// NewCreateUsersWithListInputDefault creates a CreateUsersWithListInputDefault with default headers values
func NewCreateUsersWithListInputDefault(code int) *CreateUsersWithListInputDefault {
	return &CreateUsersWithListInputDefault{
		_statusCode: code,
	}
}

/* CreateUsersWithListInputDefault describes a response with status code -1, with default header values.

successful operation
*/
type CreateUsersWithListInputDefault struct {
	_statusCode int
}

// Code gets the status code for the create users with list input default response
func (o *CreateUsersWithListInputDefault) Code() int {
	return o._statusCode
}

func (o *CreateUsersWithListInputDefault) Error() string {
	return fmt.Sprintf("[POST /user/createWithList][%d] createUsersWithListInput default ", o._statusCode)
}

func (o *CreateUsersWithListInputDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
