// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// LogoutUserReader is a Reader for the LogoutUser structure.
type LogoutUserReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LogoutUserReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	result := NewLogoutUserDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result
}

// NewLogoutUserDefault creates a LogoutUserDefault with default headers values
func NewLogoutUserDefault(code int) *LogoutUserDefault {
	return &LogoutUserDefault{
		_statusCode: code,
	}
}

/* LogoutUserDefault describes a response with status code -1, with default header values.

successful operation
*/
type LogoutUserDefault struct {
	_statusCode int
}

// Code gets the status code for the logout user default response
func (o *LogoutUserDefault) Code() int {
	return o._statusCode
}

func (o *LogoutUserDefault) Error() string {
	return fmt.Sprintf("[GET /user/logout][%d] logoutUser default ", o._statusCode)
}

func (o *LogoutUserDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
