// Code generated by go-swagger; DO NOT EDIT.

package pet

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewFindPetsByStatusParams creates a new FindPetsByStatusParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewFindPetsByStatusParams() *FindPetsByStatusParams {
	return &FindPetsByStatusParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewFindPetsByStatusParamsWithTimeout creates a new FindPetsByStatusParams object
// with the ability to set a timeout on a request.
func NewFindPetsByStatusParamsWithTimeout(timeout time.Duration) *FindPetsByStatusParams {
	return &FindPetsByStatusParams{
		timeout: timeout,
	}
}

// NewFindPetsByStatusParamsWithContext creates a new FindPetsByStatusParams object
// with the ability to set a context for a request.
func NewFindPetsByStatusParamsWithContext(ctx context.Context) *FindPetsByStatusParams {
	return &FindPetsByStatusParams{
		Context: ctx,
	}
}

// NewFindPetsByStatusParamsWithHTTPClient creates a new FindPetsByStatusParams object
// with the ability to set a custom HTTPClient for a request.
func NewFindPetsByStatusParamsWithHTTPClient(client *http.Client) *FindPetsByStatusParams {
	return &FindPetsByStatusParams{
		HTTPClient: client,
	}
}

/* FindPetsByStatusParams contains all the parameters to send to the API endpoint
   for the find pets by status operation.

   Typically these are written to a http.Request.
*/
type FindPetsByStatusParams struct {

	/* Status.

	   Status values that need to be considered for filter
	*/
	Status []string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the find pets by status params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *FindPetsByStatusParams) WithDefaults() *FindPetsByStatusParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the find pets by status params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *FindPetsByStatusParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the find pets by status params
func (o *FindPetsByStatusParams) WithTimeout(timeout time.Duration) *FindPetsByStatusParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the find pets by status params
func (o *FindPetsByStatusParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the find pets by status params
func (o *FindPetsByStatusParams) WithContext(ctx context.Context) *FindPetsByStatusParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the find pets by status params
func (o *FindPetsByStatusParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the find pets by status params
func (o *FindPetsByStatusParams) WithHTTPClient(client *http.Client) *FindPetsByStatusParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the find pets by status params
func (o *FindPetsByStatusParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithStatus adds the status to the find pets by status params
func (o *FindPetsByStatusParams) WithStatus(status []string) *FindPetsByStatusParams {
	o.SetStatus(status)
	return o
}

// SetStatus adds the status to the find pets by status params
func (o *FindPetsByStatusParams) SetStatus(status []string) {
	o.Status = status
}

// WriteToRequest writes these params to a swagger request
func (o *FindPetsByStatusParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Status != nil {

		// binding items for status
		joinedStatus := o.bindParamStatus(reg)

		// query array param status
		if err := r.SetQueryParam("status", joinedStatus...); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindParamFindPetsByStatus binds the parameter status
func (o *FindPetsByStatusParams) bindParamStatus(formats strfmt.Registry) []string {
	statusIR := o.Status

	var statusIC []string
	for _, statusIIR := range statusIR { // explode []string

		statusIIV := statusIIR // string as string
		statusIC = append(statusIC, statusIIV)
	}

	// items.CollectionFormat: "multi"
	statusIS := swag.JoinByFormat(statusIC, "multi")

	return statusIS
}
