// Code generated by go-swagger; DO NOT EDIT.

package pet

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/emcfarlane/larking/starlarkopenapi/testdata/models"
)

// FindPetsByTagsReader is a Reader for the FindPetsByTags structure.
type FindPetsByTagsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *FindPetsByTagsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewFindPetsByTagsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewFindPetsByTagsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewFindPetsByTagsOK creates a FindPetsByTagsOK with default headers values
func NewFindPetsByTagsOK() *FindPetsByTagsOK {
	return &FindPetsByTagsOK{}
}

/* FindPetsByTagsOK describes a response with status code 200, with default header values.

successful operation
*/
type FindPetsByTagsOK struct {
	Payload []*models.Pet
}

func (o *FindPetsByTagsOK) Error() string {
	return fmt.Sprintf("[GET /pet/findByTags][%d] findPetsByTagsOK  %+v", 200, o.Payload)
}
func (o *FindPetsByTagsOK) GetPayload() []*models.Pet {
	return o.Payload
}

func (o *FindPetsByTagsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewFindPetsByTagsBadRequest creates a FindPetsByTagsBadRequest with default headers values
func NewFindPetsByTagsBadRequest() *FindPetsByTagsBadRequest {
	return &FindPetsByTagsBadRequest{}
}

/* FindPetsByTagsBadRequest describes a response with status code 400, with default header values.

Invalid tag value
*/
type FindPetsByTagsBadRequest struct {
}

func (o *FindPetsByTagsBadRequest) Error() string {
	return fmt.Sprintf("[GET /pet/findByTags][%d] findPetsByTagsBadRequest ", 400)
}

func (o *FindPetsByTagsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
