// Code generated by go-swagger; DO NOT EDIT.

package pet

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new pet API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for pet API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	PostPetPetIDUploadImage(params *PostPetPetIDUploadImageParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostPetPetIDUploadImageOK, error)

	AddPet(params *AddPetParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) error

	DeletePet(params *DeletePetParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) error

	FindPetsByStatus(params *FindPetsByStatusParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*FindPetsByStatusOK, error)

	FindPetsByTags(params *FindPetsByTagsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*FindPetsByTagsOK, error)

	GetPetByID(params *GetPetByIDParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetPetByIDOK, error)

	UpdatePet(params *UpdatePetParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) error

	UpdatePetWithForm(params *UpdatePetWithFormParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) error

	SetTransport(transport runtime.ClientTransport)
}

/*
  PostPetPetIDUploadImage uploads an image
*/
func (a *Client) PostPetPetIDUploadImage(params *PostPetPetIDUploadImageParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostPetPetIDUploadImageOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostPetPetIDUploadImageParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostPetPetIDUploadImage",
		Method:             "POST",
		PathPattern:        "/pet/{petId}/uploadImage",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"multipart/form-data"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &PostPetPetIDUploadImageReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PostPetPetIDUploadImageOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostPetPetIDUploadImage: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  AddPet adds a new pet to the store
*/
func (a *Client) AddPet(params *AddPetParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) error {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewAddPetParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "addPet",
		Method:             "POST",
		PathPattern:        "/pet",
		ProducesMediaTypes: []string{"application/json", "application/xml"},
		ConsumesMediaTypes: []string{"application/json", "application/xml"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &AddPetReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	_, err := a.transport.Submit(op)
	if err != nil {
		return err
	}
	return nil
}

/*
  DeletePet deletes a pet
*/
func (a *Client) DeletePet(params *DeletePetParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) error {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeletePetParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "deletePet",
		Method:             "DELETE",
		PathPattern:        "/pet/{petId}",
		ProducesMediaTypes: []string{"application/json", "application/xml"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &DeletePetReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	_, err := a.transport.Submit(op)
	if err != nil {
		return err
	}
	return nil
}

/*
  FindPetsByStatus finds pets by status

  Multiple status values can be provided with comma separated strings
*/
func (a *Client) FindPetsByStatus(params *FindPetsByStatusParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*FindPetsByStatusOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewFindPetsByStatusParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "findPetsByStatus",
		Method:             "GET",
		PathPattern:        "/pet/findByStatus",
		ProducesMediaTypes: []string{"application/json", "application/xml"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &FindPetsByStatusReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*FindPetsByStatusOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for findPetsByStatus: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  FindPetsByTags finds pets by tags

  Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
*/
func (a *Client) FindPetsByTags(params *FindPetsByTagsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*FindPetsByTagsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewFindPetsByTagsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "findPetsByTags",
		Method:             "GET",
		PathPattern:        "/pet/findByTags",
		ProducesMediaTypes: []string{"application/json", "application/xml"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &FindPetsByTagsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*FindPetsByTagsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for findPetsByTags: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  GetPetByID finds pet by ID

  Returns a single pet
*/
func (a *Client) GetPetByID(params *GetPetByIDParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetPetByIDOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetPetByIDParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "getPetById",
		Method:             "GET",
		PathPattern:        "/pet/{petId}",
		ProducesMediaTypes: []string{"application/json", "application/xml"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetPetByIDReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetPetByIDOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getPetById: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  UpdatePet updates an existing pet
*/
func (a *Client) UpdatePet(params *UpdatePetParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) error {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewUpdatePetParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "updatePet",
		Method:             "PUT",
		PathPattern:        "/pet",
		ProducesMediaTypes: []string{"application/json", "application/xml"},
		ConsumesMediaTypes: []string{"application/json", "application/xml"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &UpdatePetReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	_, err := a.transport.Submit(op)
	if err != nil {
		return err
	}
	return nil
}

/*
  UpdatePetWithForm updates a pet in the store with form data
*/
func (a *Client) UpdatePetWithForm(params *UpdatePetWithFormParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) error {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewUpdatePetWithFormParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "updatePetWithForm",
		Method:             "POST",
		PathPattern:        "/pet/{petId}",
		ProducesMediaTypes: []string{"application/json", "application/xml"},
		ConsumesMediaTypes: []string{"application/x-www-form-urlencoded"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &UpdatePetWithFormReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	_, err := a.transport.Submit(op)
	if err != nil {
		return err
	}
	return nil
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
