// Code generated by go-swagger; DO NOT EDIT.

package pet

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/emcfarlane/larking/starlarkopenapi/testdata/models"
)

// PostPetPetIDUploadImageReader is a Reader for the PostPetPetIDUploadImage structure.
type PostPetPetIDUploadImageReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostPetPetIDUploadImageReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostPetPetIDUploadImageOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostPetPetIDUploadImageOK creates a PostPetPetIDUploadImageOK with default headers values
func NewPostPetPetIDUploadImageOK() *PostPetPetIDUploadImageOK {
	return &PostPetPetIDUploadImageOK{}
}

/* PostPetPetIDUploadImageOK describes a response with status code 200, with default header values.

successful operation
*/
type PostPetPetIDUploadImageOK struct {
	Payload *models.APIResponse
}

func (o *PostPetPetIDUploadImageOK) Error() string {
	return fmt.Sprintf("[POST /pet/{petId}/uploadImage][%d] postPetPetIdUploadImageOK  %+v", 200, o.Payload)
}
func (o *PostPetPetIDUploadImageOK) GetPayload() *models.APIResponse {
	return o.Payload
}

func (o *PostPetPetIDUploadImageOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
