// Code generated by go-swagger; DO NOT EDIT.

package pet

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewPostPetPetIDUploadImageParams creates a new PostPetPetIDUploadImageParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostPetPetIDUploadImageParams() *PostPetPetIDUploadImageParams {
	return &PostPetPetIDUploadImageParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostPetPetIDUploadImageParamsWithTimeout creates a new PostPetPetIDUploadImageParams object
// with the ability to set a timeout on a request.
func NewPostPetPetIDUploadImageParamsWithTimeout(timeout time.Duration) *PostPetPetIDUploadImageParams {
	return &PostPetPetIDUploadImageParams{
		timeout: timeout,
	}
}

// NewPostPetPetIDUploadImageParamsWithContext creates a new PostPetPetIDUploadImageParams object
// with the ability to set a context for a request.
func NewPostPetPetIDUploadImageParamsWithContext(ctx context.Context) *PostPetPetIDUploadImageParams {
	return &PostPetPetIDUploadImageParams{
		Context: ctx,
	}
}

// NewPostPetPetIDUploadImageParamsWithHTTPClient creates a new PostPetPetIDUploadImageParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostPetPetIDUploadImageParamsWithHTTPClient(client *http.Client) *PostPetPetIDUploadImageParams {
	return &PostPetPetIDUploadImageParams{
		HTTPClient: client,
	}
}

/* PostPetPetIDUploadImageParams contains all the parameters to send to the API endpoint
   for the post pet pet ID upload image operation.

   Typically these are written to a http.Request.
*/
type PostPetPetIDUploadImageParams struct {

	/* AdditionalMetadata.

	   Additional data to pass to server
	*/
	AdditionalMetadata *string

	/* File.

	   file to upload
	*/
	File runtime.NamedReadCloser

	/* PetID.

	   ID of pet to update

	   Format: int64
	*/
	PetID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post pet pet ID upload image params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostPetPetIDUploadImageParams) WithDefaults() *PostPetPetIDUploadImageParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post pet pet ID upload image params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostPetPetIDUploadImageParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post pet pet ID upload image params
func (o *PostPetPetIDUploadImageParams) WithTimeout(timeout time.Duration) *PostPetPetIDUploadImageParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post pet pet ID upload image params
func (o *PostPetPetIDUploadImageParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post pet pet ID upload image params
func (o *PostPetPetIDUploadImageParams) WithContext(ctx context.Context) *PostPetPetIDUploadImageParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post pet pet ID upload image params
func (o *PostPetPetIDUploadImageParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post pet pet ID upload image params
func (o *PostPetPetIDUploadImageParams) WithHTTPClient(client *http.Client) *PostPetPetIDUploadImageParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post pet pet ID upload image params
func (o *PostPetPetIDUploadImageParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAdditionalMetadata adds the additionalMetadata to the post pet pet ID upload image params
func (o *PostPetPetIDUploadImageParams) WithAdditionalMetadata(additionalMetadata *string) *PostPetPetIDUploadImageParams {
	o.SetAdditionalMetadata(additionalMetadata)
	return o
}

// SetAdditionalMetadata adds the additionalMetadata to the post pet pet ID upload image params
func (o *PostPetPetIDUploadImageParams) SetAdditionalMetadata(additionalMetadata *string) {
	o.AdditionalMetadata = additionalMetadata
}

// WithFile adds the file to the post pet pet ID upload image params
func (o *PostPetPetIDUploadImageParams) WithFile(file runtime.NamedReadCloser) *PostPetPetIDUploadImageParams {
	o.SetFile(file)
	return o
}

// SetFile adds the file to the post pet pet ID upload image params
func (o *PostPetPetIDUploadImageParams) SetFile(file runtime.NamedReadCloser) {
	o.File = file
}

// WithPetID adds the petID to the post pet pet ID upload image params
func (o *PostPetPetIDUploadImageParams) WithPetID(petID int64) *PostPetPetIDUploadImageParams {
	o.SetPetID(petID)
	return o
}

// SetPetID adds the petId to the post pet pet ID upload image params
func (o *PostPetPetIDUploadImageParams) SetPetID(petID int64) {
	o.PetID = petID
}

// WriteToRequest writes these params to a swagger request
func (o *PostPetPetIDUploadImageParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.AdditionalMetadata != nil {

		// form param additionalMetadata
		var frAdditionalMetadata string
		if o.AdditionalMetadata != nil {
			frAdditionalMetadata = *o.AdditionalMetadata
		}
		fAdditionalMetadata := frAdditionalMetadata
		if fAdditionalMetadata != "" {
			if err := r.SetFormParam("additionalMetadata", fAdditionalMetadata); err != nil {
				return err
			}
		}
	}

	if o.File != nil {

		if o.File != nil {
			// form file param file
			if err := r.SetFileParam("file", o.File); err != nil {
				return err
			}
		}
	}

	// path param petId
	if err := r.SetPathParam("petId", swag.FormatInt64(o.PetID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
