// Code generated by go-swagger; DO NOT EDIT.

package pet

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// UpdatePetWithFormReader is a Reader for the UpdatePetWithForm structure.
type UpdatePetWithFormReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdatePetWithFormReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 405:
		result := NewUpdatePetWithFormMethodNotAllowed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUpdatePetWithFormMethodNotAllowed creates a UpdatePetWithFormMethodNotAllowed with default headers values
func NewUpdatePetWithFormMethodNotAllowed() *UpdatePetWithFormMethodNotAllowed {
	return &UpdatePetWithFormMethodNotAllowed{}
}

/* UpdatePetWithFormMethodNotAllowed describes a response with status code 405, with default header values.

Invalid input
*/
type UpdatePetWithFormMethodNotAllowed struct {
}

func (o *UpdatePetWithFormMethodNotAllowed) Error() string {
	return fmt.Sprintf("[POST /pet/{petId}][%d] updatePetWithFormMethodNotAllowed ", 405)
}

func (o *UpdatePetWithFormMethodNotAllowed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
