// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package workerpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// WorkerClient is the client API for Worker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkerClient interface {
	RunOnThread(ctx context.Context, opts ...grpc.CallOption) (Worker_RunOnThreadClient, error)
}

type workerClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkerClient(cc grpc.ClientConnInterface) WorkerClient {
	return &workerClient{cc}
}

func (c *workerClient) RunOnThread(ctx context.Context, opts ...grpc.CallOption) (Worker_RunOnThreadClient, error) {
	stream, err := c.cc.NewStream(ctx, &Worker_ServiceDesc.Streams[0], "/larking.api.worker.Worker/RunOnThread", opts...)
	if err != nil {
		return nil, err
	}
	x := &workerRunOnThreadClient{stream}
	return x, nil
}

type Worker_RunOnThreadClient interface {
	Send(*Command) error
	Recv() (*Result, error)
	grpc.ClientStream
}

type workerRunOnThreadClient struct {
	grpc.ClientStream
}

func (x *workerRunOnThreadClient) Send(m *Command) error {
	return x.ClientStream.SendMsg(m)
}

func (x *workerRunOnThreadClient) Recv() (*Result, error) {
	m := new(Result)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// WorkerServer is the server API for Worker service.
// All implementations must embed UnimplementedWorkerServer
// for forward compatibility
type WorkerServer interface {
	RunOnThread(Worker_RunOnThreadServer) error
	mustEmbedUnimplementedWorkerServer()
}

// UnimplementedWorkerServer must be embedded to have forward compatible implementations.
type UnimplementedWorkerServer struct {
}

func (UnimplementedWorkerServer) RunOnThread(Worker_RunOnThreadServer) error {
	return status.Errorf(codes.Unimplemented, "method RunOnThread not implemented")
}
func (UnimplementedWorkerServer) mustEmbedUnimplementedWorkerServer() {}

// UnsafeWorkerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkerServer will
// result in compilation errors.
type UnsafeWorkerServer interface {
	mustEmbedUnimplementedWorkerServer()
}

func RegisterWorkerServer(s grpc.ServiceRegistrar, srv WorkerServer) {
	s.RegisterService(&Worker_ServiceDesc, srv)
}

func _Worker_RunOnThread_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WorkerServer).RunOnThread(&workerRunOnThreadServer{stream})
}

type Worker_RunOnThreadServer interface {
	Send(*Result) error
	Recv() (*Command, error)
	grpc.ServerStream
}

type workerRunOnThreadServer struct {
	grpc.ServerStream
}

func (x *workerRunOnThreadServer) Send(m *Result) error {
	return x.ServerStream.SendMsg(m)
}

func (x *workerRunOnThreadServer) Recv() (*Command, error) {
	m := new(Command)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Worker_ServiceDesc is the grpc.ServiceDesc for Worker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Worker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "larking.api.worker.Worker",
	HandlerType: (*WorkerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RunOnThread",
			Handler:       _Worker_RunOnThread_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "apipb/workerpb/worker.proto",
}
