// Code generated by go-swagger; DO NOT EDIT.

package store

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeleteOrderParams creates a new DeleteOrderParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteOrderParams() *DeleteOrderParams {
	return &DeleteOrderParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteOrderParamsWithTimeout creates a new DeleteOrderParams object
// with the ability to set a timeout on a request.
func NewDeleteOrderParamsWithTimeout(timeout time.Duration) *DeleteOrderParams {
	return &DeleteOrderParams{
		timeout: timeout,
	}
}

// NewDeleteOrderParamsWithContext creates a new DeleteOrderParams object
// with the ability to set a context for a request.
func NewDeleteOrderParamsWithContext(ctx context.Context) *DeleteOrderParams {
	return &DeleteOrderParams{
		Context: ctx,
	}
}

// NewDeleteOrderParamsWithHTTPClient creates a new DeleteOrderParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteOrderParamsWithHTTPClient(client *http.Client) *DeleteOrderParams {
	return &DeleteOrderParams{
		HTTPClient: client,
	}
}

/* DeleteOrderParams contains all the parameters to send to the API endpoint
   for the delete order operation.

   Typically these are written to a http.Request.
*/
type DeleteOrderParams struct {

	/* OrderID.

	   ID of the order that needs to be deleted

	   Format: int64
	*/
	OrderID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete order params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteOrderParams) WithDefaults() *DeleteOrderParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete order params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteOrderParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete order params
func (o *DeleteOrderParams) WithTimeout(timeout time.Duration) *DeleteOrderParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete order params
func (o *DeleteOrderParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete order params
func (o *DeleteOrderParams) WithContext(ctx context.Context) *DeleteOrderParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete order params
func (o *DeleteOrderParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete order params
func (o *DeleteOrderParams) WithHTTPClient(client *http.Client) *DeleteOrderParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete order params
func (o *DeleteOrderParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrderID adds the orderID to the delete order params
func (o *DeleteOrderParams) WithOrderID(orderID int64) *DeleteOrderParams {
	o.SetOrderID(orderID)
	return o
}

// SetOrderID adds the orderId to the delete order params
func (o *DeleteOrderParams) SetOrderID(orderID int64) {
	o.OrderID = orderID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteOrderParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param orderId
	if err := r.SetPathParam("orderId", swag.FormatInt64(o.OrderID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
