// Code generated by go-swagger; DO NOT EDIT.

package store

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteOrderReader is a Reader for the DeleteOrder structure.
type DeleteOrderReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteOrderReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 400:
		result := NewDeleteOrderBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteOrderNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteOrderBadRequest creates a DeleteOrderBadRequest with default headers values
func NewDeleteOrderBadRequest() *DeleteOrderBadRequest {
	return &DeleteOrderBadRequest{}
}

/* DeleteOrderBadRequest describes a response with status code 400, with default header values.

Invalid ID supplied
*/
type DeleteOrderBadRequest struct {
}

func (o *DeleteOrderBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /store/order/{orderId}][%d] deleteOrderBadRequest ", 400)
}

func (o *DeleteOrderBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteOrderNotFound creates a DeleteOrderNotFound with default headers values
func NewDeleteOrderNotFound() *DeleteOrderNotFound {
	return &DeleteOrderNotFound{}
}

/* DeleteOrderNotFound describes a response with status code 404, with default header values.

Order not found
*/
type DeleteOrderNotFound struct {
}

func (o *DeleteOrderNotFound) Error() string {
	return fmt.Sprintf("[DELETE /store/order/{orderId}][%d] deleteOrderNotFound ", 404)
}

func (o *DeleteOrderNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
