// Code generated by go-swagger; DO NOT EDIT.

package store

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/emcfarlane/larking/starlarkopenapi/testdata/models"
)

// NewPlaceOrderParams creates a new PlaceOrderParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPlaceOrderParams() *PlaceOrderParams {
	return &PlaceOrderParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPlaceOrderParamsWithTimeout creates a new PlaceOrderParams object
// with the ability to set a timeout on a request.
func NewPlaceOrderParamsWithTimeout(timeout time.Duration) *PlaceOrderParams {
	return &PlaceOrderParams{
		timeout: timeout,
	}
}

// NewPlaceOrderParamsWithContext creates a new PlaceOrderParams object
// with the ability to set a context for a request.
func NewPlaceOrderParamsWithContext(ctx context.Context) *PlaceOrderParams {
	return &PlaceOrderParams{
		Context: ctx,
	}
}

// NewPlaceOrderParamsWithHTTPClient creates a new PlaceOrderParams object
// with the ability to set a custom HTTPClient for a request.
func NewPlaceOrderParamsWithHTTPClient(client *http.Client) *PlaceOrderParams {
	return &PlaceOrderParams{
		HTTPClient: client,
	}
}

/* PlaceOrderParams contains all the parameters to send to the API endpoint
   for the place order operation.

   Typically these are written to a http.Request.
*/
type PlaceOrderParams struct {

	/* Body.

	   order placed for purchasing the pet
	*/
	Body *models.Order

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the place order params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PlaceOrderParams) WithDefaults() *PlaceOrderParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the place order params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PlaceOrderParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the place order params
func (o *PlaceOrderParams) WithTimeout(timeout time.Duration) *PlaceOrderParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the place order params
func (o *PlaceOrderParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the place order params
func (o *PlaceOrderParams) WithContext(ctx context.Context) *PlaceOrderParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the place order params
func (o *PlaceOrderParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the place order params
func (o *PlaceOrderParams) WithHTTPClient(client *http.Client) *PlaceOrderParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the place order params
func (o *PlaceOrderParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the place order params
func (o *PlaceOrderParams) WithBody(body *models.Order) *PlaceOrderParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the place order params
func (o *PlaceOrderParams) SetBody(body *models.Order) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PlaceOrderParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
